---
- name: Service Restart Remediation
  hosts: "{{ target_hosts | default('all') }}"
  become: yes
  vars:
    service_name: "{{ service_to_restart }}"

  tasks:
    - name: Get service status (Linux)
      ansible.builtin.service_facts:
      when: ansible_facts['os_family'] == "Linux"

    - name: Restart service on Linux
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
      when: ansible_facts['os_family'] == "Linux"
      register: linux_restart

    - name: Restart service on Windows
      win_service:
        name: "{{ service_name }}"
        state: restarted
      when: ansible_facts['os_family'] == "Windows"
      register: windows_restart

    - name: Verify service status after restart (Linux)
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: started
      when: ansible_facts['os_family'] == "Linux"

    - name: Verify service status after restart (Windows)
      win_service:
        name: "{{ service_name }}"
        state: started
      when: ansible_facts['os_family'] == "Windows"
